#!/bin/bash

# Argument check
if [ ! $# == 2 ]; then
  echo "Usage: $0 template_name destination_dir"
  exit
fi

# Path to script 
SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Path to template folder
TEMPLATE="$SCRIPT/sources/$1"

# Check if template exists
if [ -d "$TEMPLATE" ]; then
    if [ -d "$2" ] && [ "$(ls -A $2)" ]; then
        echo "Template not created, files exist in $2"
    else
        cp -r -T "$TEMPLATE" "$2"
        echo "Template created successfully"
    fi
else
    echo "Template not found."
fi